api/urls.py
"""ursl shema for api v1"""
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views import UserAPICreate, UserAPIDetailView
from django.urls import path, include, re_path


urlpatterns = [
    # djoser
    path('auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view(), name='token_verify'),
    # djoser
    # auth
    path('auth/register/', UserAPICreate.as_view()),
    path('auth/update/<int:pk>/', UserAPIDetailView.as_view()),
    # auth
]

authentication/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.main, name='main'),
    path('profile/', views.profile_view, name='profile'),
    path('accounts/login/', views.MyLoginView.as_view(), name='account_login'),
    path('login/verification/', views.verification, name='verification'),
    path('accounts/logout/', views.MyLogoutView.as_view(), name='account_logout'),
    path('accounts/googlelogin/', views.google_login, name='google_login'),
    path('webhook/task/', views.webhook_task, name='webhook_task'),
    path('webhook/invoice/', views.webhook_invoice, name='webhook_invoice'),
    path('webhook/service_section/', views.webhook_service_section),
    path('webhook/task/comment_add/', views.webhook_task_comment, name='webhook_task_comment'),
    path('ajax_errors/', views.ajax_errors),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nexxes_proj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('api.urls')),
    path('invoices/', include('invoices.urls')),
    path('tickets/', include('tickets.urls')),
    path('services/', include('services.urls')),
    path('support/', include('support.urls')),
    path('telegram/', include('telegram_bot.urls')),

    path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views

app_name = 'services'


urlpatterns = [
    # services pages
    path('', views.services, name='services'),
    path('my_services/', views.my_services, name='my_services'),
    path('create_invoice/', views.create_invoice, name='create_invoice'),
    path('about_service/<int:id>/', views.product_detail, name='product_detail'),
    # path('service_1/', views.service_1, name='service1'),
    # path('service_2/', views.service_2, name='service2'),
    # path('service_3/', views.service_3, name='service3'),
    path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tickets/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views


app_name = 'tickets'

urlpatterns = [
    path('', views.tasks, name='tasks'),
    path('list', views.task_data, name='list'),
    path('create-task/', views.create_bitrix_task, name='create_task'),
    path('detail/<int:id>/', views.task_detail, name="task_detail"),
    path('ajax_tasks_filter/', views.ajax_tasks_filter),
    path('send_user_message/', views.send_user_message, name="send_user_message"),
    path('search/', include('search.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/views/Main.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.shortcuts import render, redirect

from authentication.helpers.B24Webhook import set_webhook
from tickets.models import Ticket, TicketStatus
from invoices.models import Invoice

import requests
from authentication.helpers.B24Webhook import set_webhook
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView




class TestView(TemplateView):
    template_name = 'test.html'


@login_required(login_url='/accounts/login/')
def main(request):
    try:
        if request.user.is_superuser:
            invoice_count = Invoice.objects.all().exclude(status__value='Opened').count()
            task_count = Ticket.objects.filter(is_opened=False).count()
            current_user = "admin"



        else:
            invoice_count = Invoice.objects.filter(responsible=request.user.b24_contact_id).exclude(status__value='Paid').exclude(status__value='Opened').count()
            task_count = Ticket.objects.filter(responsible=str(request.user.b24_contact_id), is_opened=False).count()
            current_user = "not_admin"
            ticket_statuses = TicketStatus.objects.filter(ticket__responsible=str(request.user.b24_contact_id)).distinct()
            b_services = Invoice.objects.filter(responsible=request.user.b24_contact_id).exclude(status__value='Opened').count()

            b_services = Invoice.objects.filter(responsible=request.user.b24_contact_id).exclude(status__value='Opened').exclude(status__value='New').count()

        method = "crm.product.list"
        url = set_webhook(method)
        product_count = requests.get(url).json()['total']



        all_user_tickets = Ticket.objects.all().order_by('-created_at') if request.user.is_superuser \
            else Ticket.objects.filter(responsible=request.user.b24_contact_id).order_by('-created_at')

        bought_services = Invoice.objects.filter(responsible=str(request.user.b24_contact_id), status__value='Paid')

        all_tickets_statuses = TicketStatus.objects.all()
        tickets_statuses = list()
        status_check = list()

        for ticket in all_user_tickets:
            for ticket_status in all_tickets_statuses:

                if ticket_status.name == ticket.status.name:
                    ticket_status_quantity = all_user_tickets.filter(status__name=ticket_status.name).count()

                    if ticket.status.name not in status_check:
                        status_check.append(ticket.status.name)
                        tickets_statuses.append({
                                        'name': ticket.status.name,
                                        'color': ticket.status.color,
                                        'number': ticket_status_quantity
                                        })

        res = {
            'invoice_count': invoice_count,
            'task_count': task_count,
            'services_all_count': product_count,
            'current_user': current_user,
            'ticket_statuses': ticket_statuses,
            'b_services': b_services,
            'statuses': tickets_statuses,

        }

    except:
        res = {
            'invoice_count': "0",
            'task_count': "0",
            'services_all_count': "0",
        }

    if request.user.is_superuser:
        return render(request, "main_superuser.html", res)

    else:
        return render(request, "main.html", res)

authentication/views/profile.py
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.http import JsonResponse

from authentication.helpers.B24Webhook import set_webhook
from telegram_bot.models import User
from tickets.models import Ticket, TicketStatus
from invoices.models import Invoice

from bitrix24 import *


@login_required(login_url='/accounts/login/')
def profile_view(request):
    user = User.objects.filter(id=request.user.id)
    if user.exists():
        user = user.first()

    if user.is_superuser:
        user_tickets = Ticket.objects.all().order_by('-created_at')
    else:
        user_tickets = Ticket.objects.filter(responsible=user.b24_contact_id).order_by('-created_at')

    paid_services = Invoice.objects.filter(responsible=str(user.b24_contact_id), status__value='Paid')

    tickets_statuses = TicketStatus.objects.all()
    statuses_list = list()
    status_check = list()

    for ticket in user_tickets:
        for ticket_status in tickets_statuses:

            if ticket_status.name == ticket.status.name:
                ticket_status_quantity = user_tickets.filter(status__name=ticket_status.name).count()

                if ticket.status.name not in status_check:
                    status_check.append(ticket.status.name)
                    statuses_list.append({
                        'name': ticket.status.name,
                        'color': ticket.status.color,
                        'number': ticket_status_quantity
                    })

    if request.method == 'POST':

        if request.FILES:
            if request.FILES['profile_image'].size < (2 * 1024 * 1024):
                file = request.FILES['profile_image']
                default_storage.save(file.name, file)  # Save image to /media/
                user.photo = file.name

        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        phone = request.POST.get('phone', '')
        bio = request.POST.get('bio', '')

        country = request.POST.get('country', '')
        city = request.POST.get('city', '')
        street = request.POST.get('street', '')
        tax_id = request.POST.get('tax_id', '')

        old_password = request.POST.get('old_password', '')
        new_password = request.POST.get('new_password', '')

        check_list = [first_name, last_name, phone, bio, country, city, street, tax_id, old_password]

        if new_password == '':
            try:
                user.first_name = first_name if first_name else user.first_name
                user.last_name = last_name if last_name else user.last_name
                user.phone = phone if phone else user.phone
                user.bio = bio if bio else user.bio

                user.country = country if country else user.country
                user.city = city if city else user.city
                user.street = street if street else user.street
                user.tax_id = tax_id if tax_id else user.tax_id

                url = set_webhook()
                bx24 = Bitrix24(url)
                bx24.callMethod(
                    'user.update',
                    ID=312,  # user.b24_contact_id
                    NAME=user.first_name,
                    LAST_NAME=user.last_name,
                    PERSONAL_MOBILE=user.phone,
                    WORK_POSITION=user.bio,
                    PERSONAL_COUNTRY=user.country,
                    PERSONAL_CITY=user.city,
                    PERSONAL_STREET=user.street,
                    UF_TAX_ID=user.tax_id
                )
                user.save()
            except BitrixError as bitrix_error:
                print(' ---- The data could not be updated due to this error: ---- \n' + str(bitrix_error))

            return redirect('/profile/')

        elif '' not in check_list and len(new_password) > 7 and any([authenticate(request, username=user.email, password=old_password), all([old_password == user.password, len(old_password) == 41])], ):
            try:
                user.first_name = first_name if first_name else user.first_name
                user.last_name = last_name if last_name else user.last_name
                user.phone = phone if phone else user.phone
                user.bio = bio if bio else user.bio

                user.country = country if country else user.country
                user.city = city if city else user.city
                user.street = street if street else user.street
                user.tax_id = tax_id if tax_id else user.tax_id

                url = set_webhook()
                bx24 = Bitrix24(url)
                bx24.callMethod(
                    'user.update',
                    ID=312,  # user.b24_contact_id
                    NAME=user.first_name,
                    LAST_NAME=user.last_name,
                    PERSONAL_MOBILE=user.phone,
                    WORK_POSITION=user.bio,
                    PERSONAL_COUNTRY=user.country,
                    PERSONAL_CITY=user.city,
                    PERSONAL_STREET=user.street,
                    UF_TAX_ID=user.tax_id
                )

                user.set_password(new_password)
                user.google_auth = False
                user.save()

            except BitrixError as bitrix_error:
                print(' ---- The data could not be updated due to this error: ---- \n' + str(bitrix_error))

            return redirect('/accounts/login/')

        else:
            return redirect('/profile/')

    user.first_name = user.first_name if user.first_name else 'Empty'
    user.last_name = user.last_name if user.last_name else 'Empty'
    user.phone = user.phone if user.phone else 'Empty'
    user.bio = user.bio if user.bio else 'Empty'

    user.country = user.country if user.country else 'Empty'
    user.city = user.city if user.city else 'Empty'
    user.street = user.street if user.street else 'Empty'
    user.tax_id = user.tax_id if user.tax_id else 'Empty'

    context = {
        'user': user,
        'statuses': statuses_list,
        'paid_services': paid_services,
    }

    return render(request, 'profile.html', context)


def ajax_errors(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':

        if request.method == 'POST':
            response = {
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'phone': request.user.phone,
                'bio': request.user.bio,
                'country': request.user.country,
                'city': request.user.city,
                'street': request.user.street,
                'tax_id': request.user.tax_id,
            }

            return JsonResponse(response)

telegram_bot/views/Main.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import HttpResponse
from telegram import Bot

from .Helper import SettingsHelper

from ..handlers import MessageHandler, CallbackHandler

import logging
import json


logger = logging.getLogger(__name__)


@csrf_exempt
def main(request):
    api_token = SettingsHelper.get_bot_token()
    bot = Bot(token=api_token)

    if request.method == 'POST':
        data = json.loads(request.body)

        if 'message' in data:
            message_handler = MessageHandler(bot, data)
            message_handler.handle_request()

            # Message logger credentials
            telegram_username = data['message']['from']['username']
            telegram_user_id = data['message']['from']['id']

            if 'text' in data['message'].keys():
                user_message = data['message']['text']
                logger.info(f'Message: {telegram_username} {telegram_user_id} - {user_message}')

            elif 'successful_payment' in data['message'].keys():
                amount = data['message']['successful_payment']['total_amount'] / 100
                currency = data['message']['successful_payment']['currency']
                invoice_payload = data['message']['successful_payment']['invoice_payload']

                logger.info(f'Successful payment: {telegram_username} ({telegram_user_id}) - {amount} {currency} {invoice_payload}')

            else:
                logger.info(f'Message: {telegram_username} ({telegram_user_id}) - Not text')

        elif 'callback_query' in data:
            callback_handler = CallbackHandler(bot, data)
            callback_handler.handle_request()

            # Callback logger credentials
            telegram_username = data['callback_query']['from']['username']
            telegram_user_id = data['callback_query']['from']['id']
            user_callback_data = data['callback_query']['data']

            button_title = ''
            inline_keyboard = data["callback_query"]["message"]["reply_markup"]["inline_keyboard"]
            for i in range(len(inline_keyboard)):
                for j in range(len(inline_keyboard[i])):
                    for key, value in inline_keyboard[i][j].items():
                        if value == data['callback_query']['data']:
                            button_title = inline_keyboard[i][j]['text']

            logger.info(f'Callback: {telegram_username} ({telegram_user_id}) - {button_title} ({user_callback_data})')

        elif 'pre_checkout_query' in data:
            callback_handler = CallbackHandler(bot, data)
            callback_handler.handle_request()

            # Payment logger credentials
            telegram_username = data['pre_checkout_query']['from']['username']
            telegram_user_id = data['pre_checkout_query']['from']['id']
            pre_checkout_query_id = data['pre_checkout_query']['id']

            logger.info(f'Callback: {telegram_username} ({telegram_user_id}) - {pre_checkout_query_id}')

    return HttpResponse('')

templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load account %}
{% load socialaccount %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="shortcut icon" href="{% static 'images/main/favicon.ico' %}" type="image/x-icon">
    {% block extra_css %}
    {% endblock %}
    <title>{% block title %} NEXXESS {% endblock %}</title>
</head>
<body>


    {% if user.google_auth  or user.is_superuser %}
        <header class="header">
          <div class="container">
            <div class="header__inner">
              <a href="{% url 'authentication:main'%}">
                <img class="header__logo-img" src="{% static 'images/logo.svg' %}" alt="logo">
              </a>


              <div class="content__top-search">
                <img class="header__search-img" src="{% static 'images/main/Search.svg' %}" alt="Search">
                <form id="search-form" autocomplete="off">
                  {% csrf_token %}
                  <input class="content__top-input" type="search" type="text" id="gs-input" placeholder="Search">
                </form>

                <div id='general_results_box' class='general-results-card not-visible'></div>
              </div>

              <nav class="nav">
                <ul class="nav__list">
                  <li class="nav__list-item">
                    <div class="nav__list-item-link-inner">
                      <a class="{% if "/services/" == request.path %} nav__item-link {% else %} nav__item-link{% endif %}" href="{% url 'services:services' %}">
                        Services
                      </a>
                      <span class="nav__item-link-arrow">
                        <svg width="15px" height="15px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

                          <g id="SVGRepo_bgCarrier" stroke-width="0" />

                          <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" />

                          <g id="SVGRepo_iconCarrier">
                            <path
                              d="M17.9188 8.17969H11.6888H6.07877C5.11877 8.17969 4.63877 9.33969 5.31877 10.0197L10.4988 15.1997C11.3288 16.0297 12.6788 16.0297 13.5088 15.1997L15.4788 13.2297L18.6888 10.0197C19.3588 9.33969 18.8788 8.17969 17.9188 8.17969Z"
                              fill="#5B66E3" />
                          </g>

                        </svg>
                      </span>
                    </div>

                    <ul class="nav__sublist">
                      {% for category in categories %}
                      <li class="nav__subitem">
                        <a href="{% url 'services:product_detail' category.category_b24_id %}" class="nav__subitem-link">
                          {{category.category_name}}
                        </a>
                      </li>
                      {% endfor %}

                      <li class="nav__subitem">
                        <a href="{% url 'services:my_services' %}" class="nav__subitem-link">
                          My Services
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav__list-item">
                    <a class="{% if "/invoices/" == request.path %} nav__item-link {% else %} nav__item-link{% endif %}"
                      href="{% url 'invoices' %}">
                      Invoices

                    </a>
                  </li>
                  <li class="nav__list-item">
                    <div class="nav__list-item-link-inner">
                      <a class="{% if " /tickets/" == request.path %} nav__item-link {% else %} nav__item-link{% endif %}"
                        href="{% url 'tickets:list' %}">Tickets
                      </a>
                      <span class="nav__item-link-arrow">
                        <svg width="15px" height="15px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

                          <g id="SVGRepo_bgCarrier" stroke-width="0" />

                          <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" />

                          <g id="SVGRepo_iconCarrier">
                            <path
                              d="M17.9188 8.17969H11.6888H6.07877C5.11877 8.17969 4.63877 9.33969 5.31877 10.0197L10.4988 15.1997C11.3288 16.0297 12.6788 16.0297 13.5088 15.1997L15.4788 13.2297L18.6888 10.0197C19.3588 9.33969 18.8788 8.17969 17.9188 8.17969Z"
                              fill="#5B66E3" />
                          </g>

                        </svg>
                      </span>
                    </div>

                    <ul class="nav__sublist">
                      <li class="nav__subitem">
                        <a href="{% url 'tickets:tasks' %}" class="nav__subitem-link">
                          My Tickets
                        </a>
                      </li>

                      <li class="nav__subitem">
                        <a href="{% url 'tickets:list' %}" class="nav__subitem-link">
                          Create a Ticket
                        </a>
                      </li>
                    </ul>

                  </li>
                  <li class="nav__list-item">
                    <a class="{% if " /support/" == request.path %} nav__item-link {% else %} nav__item-link{% endif %}"
                      href="{% url 'support' %}">FAQ</a>
                  </li>
                  <li class="nav__list-item">
                    <a class="{% if " /support/" == request.path %} nav__item-link {% else %} nav__item-link{% endif %}"
                      href="{% url 'support' %}">Refer a Friend</a>
                  </li>
                </ul>
              </nav>
              <div class="header__box">
                <span class="header__box-link header__box-link-sublist">
                  <img class="header__box-img" src="{% static 'images/user.svg' %}" alt="user">
                  <ul class="header__box-link-list">
                    <li class="header__box-link-item">
                      <a href="{% url 'authentication:profile' %}" class="header__box-link-sublink">
                        Settings
                      </a>
                    </li>

                    <li class="header__box-link-item">
                      <a href="{% url 'account_logout'%}" class="header__box-link-sublink">
                        Logout
                      </a>
                    </li>
                  </ul>
                </span>
                <a class="header__box-link" href="https://t.me/Nexxess_Avivi_bot">
                  <img class="header__box-img" title="Go to Telegram bot" src="{% static 'images/telegram.svg' %}" alt="user">
                </a>
                <a class="burger">
                  <span class="burger-line"></span>
                </a>
              </div>
            </div>
        </header>
        <main class="main">
          <div class="container">

            <div class="main__inner">

                <aside class="aside">
                    {% block left_menu %}
                    {% endblock left_menu %}
                </aside>

                <section class="content">
                  {% block task %}
                  {% endblock %}
                    {% block content %}
                    {% endblock content %}

                </section>

                <section class="cabinet">
                    {% block cabinet %}
                    {% endblock cabinet %}
                </section>

            </div>
          </div>
        </main>
    {% else %}
        {% block auth %}
        {% endblock auth %}
    {% endif %}
    <footer class="footer">
        {% block footer %}
        {% endblock footer %}
    </footer>
    {% block extra_js %}
    {% endblock %}
</body>
</html>